kemenkumham : "https://www.kemenkumham.go.id/rss/rss-newskumham"
antaranews_hukum : "https://www.antaranews.com/rss/hukum.xml"
antaranews_politik : "https://www.antaranews.com/rss/politik.xml"
antaranews_kriminalitas : "https://www.antaranews.com/rss/metro-kriminalitas.xml"
vice_indonesia : "https://www.vice.com/id/rss?locale=id_id"
cnn_indonesia : "https://www.cnnindonesia.com/nasional/rss"
cnbc_indonesia : "https://www.cnbcindonesia.com/news/rss"
cyware_cybersecurity : "https://cyware.com/allnews/feed"
f5_threats : "https://www.f5.com/labs/rss-feeds/threats.xml"
